# Generated by Django 5.1.2 on 2025-01-07 22:22

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.JSONField(validators=[events.models.validate_categories]),
        ),
    ]
